
name: Aviator Bot

on:
  push:
    branches: [main]  # Trigger on push to main
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Auto-cancel if it runs too long

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node server.js

      - name: Print finished
        run: echo "Bot run completed."
